name = "typescript-do-worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
dir = "dist"
main = "./worker.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]
